# File returns the GStreamer configuration for a static build
import os
from typing import List

def get_gst_config(install_prefix: str, build_prefix: str, build_type: str) -> List[str]:
    return ["meson", "setup", "--wipe", f"--buildtype={build_type}", f"--prefix={install_prefix}",
            "-Dstrip=false",
            "--default-library=static",
            "-Dgst-full-target-type=static_library",
            "--wrap-mode=forcefallback",
            "-Dgst-full-libraries=*",
            "-Dauto_features=disabled",
            "-Dbase=enabled",
            "-Dgood=enabled",
            "-Dbad=enabled",
            "-Dtools=enabled",
            "-Dtests=disabled",
            "-Dlibnice=enabled",
            "-Dlibav=disabled",
            "-Drtsp_server=disabled",
            "-Dglib:tests=false",
            "-Dcustom_subprojects=json-glib",
            "-Djson-glib:default_library=static",
            "-Djson-glib:tests=false",
            "-Dpcre2:test=false",
            "-Dges=disabled",
            "-Ddevtools=disabled",
            "-Dpython=disabled",
            "-Dgstreamer:registry=false",
            "-Dgst-plugins-base:playback=enabled",
            "-Dgst-plugins-base:encoding=enabled",
            "-Dgst-plugins-base:subparse=enabled",
            "-Dgst-plugins-base:compositor=enabled",
            "-Dgst-plugins-base:videotestsrc=enabled",
            "-Dgst-plugins-base:videorate=enabled",
            "-Dgst-plugins-base:videoconvertscale=enabled",
            "-Dgst-plugins-base:app=enabled",
            "-Dgst-plugins-base:typefind=enabled",
            "-Dgst-plugins-base:examples=disabled",
            "-Dgst-plugins-base:tests=disabled",
            "-Dgst-plugins-good:qt6=enabled",
            "-Dgst-plugins-good:soup=enabled",
            "-Dgst-plugins-good:rtp=enabled",
            "-Dgst-plugins-good:isomp4=enabled",
            "-Dgst-plugins-good:examples=disabled",
            "-Dgst-plugins-good:tests=disabled",
            "-Dgst-plugins-bad:autoconvert=enabled",
            "-Dgst-plugins-bad:d3d11=enabled",
            "-Dgst-plugins-bad:qt6d3d11=enabled",
            "-Dgst-plugins-bad:d3dvideosink=disabled",
            "-Dgst-plugins-bad:nvcodec=disabled",
            "-Dgst-plugins-bad:webrtc=enabled",
            "-Dgst-plugins-bad:videoparsers=enabled",
            "-Dgst-plugins-bad:examples=disabled",
            "-Dgst-plugins-bad:tests=disabled",
            "--vsenv",
            build_prefix
                                ]



